###
POST http://localhost:3000/api/users
Content-Type: application/application/json

{
    "first_name":"peter",
    "last_name":"mburu",
    "email":"peterwahu0@gmail.com",
    "password":"peter"
}

### all users
GET  http://localhost:3000/api/users


### one users
GET http://localhost:3000/api/users/646b1fd1-b04e-4729-9a05-51d8cc28023e
### delete user
DELETE http://localhost:3000/api/users/ad7bff7e-882a-4c9e-85d0-a4d5538f2a65